### ISSUE TITLE
DATA VALIDATIONS: ORDER

### ISSUE THREAD

**Issue by Miheegz** [Chris-and-his-Mihigos/grace-shopper#45]
Orders must belong to a user OR guest session (authenticated vs unauthenticated)											
Orders must contain line items that capture the price, current product ID and quantity											
If a user completes an order, that order should keep the price of the item at the time when they checked out even if the price of the product later changes

**Comment by mtamahori** [comment]
done but can only confirm once we have admin functionality for changing product information
